# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Fails if there are any ">>>>>" lines in files due to merge conflicts.
      - id: check-merge-conflict
      # Trims trailing whitespace. Allow a single space on the end of .md lines for hard line breaks.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Makes sure files end in a newline and only a newline;
      - id: end-of-file-fixer
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
      - id: check-yaml
        args: ["--unsafe"]
      # Check for symlinks that do not point to anything.
      - id: check-symlinks
      # Fail if staged files are above a certain size.
      - id: check-added-large-files
        args: ["--maxkb=500"]
      # Sort requirements in requirements.txt files.
      - id: requirements-txt-fixer
      # Prevent addition of new git submodules.
      - id: forbid-new-submodules
      # Prevent committing directly to trunk
      - id: no-commit-to-branch
        args: ["--branch=main"]
      # Detects the presence of private keys
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
        # Run the linter.
        - id: ruff
          args: [--config=./pyproject.toml]
        # Run the formatter.
        - id: ruff-format
          args: [--config=./pyproject.toml]
